# apiVersion: v1
# kind: Pod
# metadata:
#   name: auto-scaler
#   annotations:
#     "sidecar.istio.io/inject": "false"
# spec:
#   containers:
#   - name: auto-scaler
#     image: mirage20/k8s-debug-tools
#   nodeSelector:
#     type: auto-scaler

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-scaler
  labels:
    app: auto-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-scaler
  template:
    metadata:
      labels:
        app: auto-scaler
    spec:
      containers:
      - name: auto-scaler
        image: anushiya/auto-scaler:v1
        resources:
            limits:
                cpu: "100m"
            requests:
                cpu: "100m"
      nodeSelector:
        type: auto-scaler