apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-scaler
  labels:
    app: auto-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-scaler
  template:
    metadata:
      labels:
        app: auto-scaler
    spec:
      containers:
      - name: auto-scaler
        image: anushiya/auto-scaler:v1
        imagePullPolicy: Always
        resources:
            limits:
                cpu: "100m"
            requests:
                cpu: "100m"
      nodeSelector:
        type: auto-scaler