apiVersion: v1
kind: Pod
metadata:
  name: monitoring-server
  annotations:
    "sidecar.istio.io/inject": "false"
spec:
  containers:
  - name: monitoring
    image: mirage20/k8s-debug-tools
  nodeSelector:
    type: auto-scaler
