apiVersion: batch/v1
kind: Job
metadata:
  name: perf-test-job
spec:
  template:
    spec:
      containers:
      - name: perf-test-job
        image: anushiya/performance-test:v1
        imagePullPolicy: Always
        command: ["bash", "run_performance_test.sh"]
        volumeMounts:
        - mountPath: "/home/jmeter/results"
          name: pv-storage
      restartPolicy: Never
      nodeSelector:
        type: auto-scaler
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: pv-claim
  backoffLimit: 4
